---
- name: Installing openssh-sftp-server
  community.general.opkg:
    name: openssh-sftp-server
    state: present
  when: install_sftp == "true"

- name: Install filesystem manipulation packages
  community.general.opkg:
    name:
      - kmod-nvme
      - mmc-utils
      - kmod-mtd-rw
      - kmod-fs-ext4
      - lsblk
      - parted
      - blkid
      - uvol
      - autopart
      - openssl-util
    state: present
