---
certificate_path: "../../{{ cert_path }}"
authorized_keys_path: "../../{{ key_path }}"
bpi_password: "MaybeUw1llChangeThis!"
bpi_hostname: "bpi-r3"

# Radio
radio_ssid: "bpi_test"
radio_password: "1willModify!tS00n"

# the bpi will get its network part from the CIDR
bpi_ip: "1"

# set this to false if you do not want the NVMe formated everytime the site.yaml playbook is run.
always_format_nvme: "true"

# if you don't need full python installed, change this to "true"
# if you set it to "true", add validate_certs=false to ansible.cfg
save_space_with_python3_light: "false"

# use dnsmasq or odhcpd?
replace_dnsmasq_with_odhcpd: "true"

# by default, if we do not install sftp, ansible will generate warnings
# fix this in ansible.cfg by setting transfer to "scp" instead of "sftp"
# or install openssh_sftp
sftp_install: "false"

### PowerDNS
pdns_install: "true"
# Remove PowerDNS database everytime you run playbook, then create and populate it
pdns_remove_db: "false"

### vsftpd
vsftpd_install: "false"

### openVPN
openvpn_install: "false"

prometheus_exporter_install: "false"
