---
- name: Bootstrap python on Banana PI/OpenWRT
  hosts: openwrt
  gather_facts: false
  become: false
  vars_files:
    - host_vars/banana_pi_r3.yaml
  roles:
    - role: 'johanneskastl.bootstrap_python_on_OpenWRT'

- name: Setup the host
  hosts: openwrt
  vars_files:
    - group_vars/global_vars.yaml
    - host_vars/banana_pi_r3.yaml
  roles:
    - bpi-r3-host-setup

- name: Setup DHCP
  hosts: openwrt
  vars_files:
    - group_vars/global_vars.yaml
    - host_vars/banana_pi_r3.yaml
  roles:
    - dhcp

- name: Disabling IPv6
  hosts: openwrt
  vars_files:
    - group_vars/global_vars.yaml
    - host_vars/banana_pi_r3.yaml
  roles:
    - role: bpi-r3-disable-ipv6
      when: disable_ipv6 == "true"
  tags:
    - ipv6
  
- name: Checking for NVMe and mounting it
  hosts: openwrt
  vars_files:
    - host_vars/banana_pi_r3.yaml
  roles:
    - nvme
  tags:
    - nvme

- name: Installing Luci with NGinx and SSL
  hosts: openwrt
  vars_files:
    - host_vars/banana_pi_r3.yaml
  roles:
    - bpi-r3-additional-packages

- name: Copying and registering our own Certificate Authority
  hosts: openwrt
  vars_files:
    - group_vars/global_vars.yaml
    - host_vars/banana_pi_r3.yaml
  roles:
    - bpi-r3-certs

- name: Configuring PowerDNS and its recursor
  hosts: openwrt
  gather_facts: true
  vars_files:
    - host_vars/banana_pi_r3.yaml
    - group_vars/global_vars.yaml
  roles:
    - pdns
  tags:
    - pdns

- name: Configuring vsftpd
  hosts: openwrt
  gather_facts: true
  vars_files:
    - host_vars/banana_pi_r3.yaml
    - group_vars/global_vars.yaml
  roles:
    - role: vsftpd
      when: vsftpd_install == "true"
