---
- name: Bootstrap python on Banana PI/OpenWRT
  hosts: openwrt
  gather_facts: false
  become: false
  vars_files:
    - host_vars/banana_pi_r3.yaml
  roles:
    - role: 'johanneskastl.bootstrap_python_on_OpenWRT'

- name: Setup the host
  hosts: openwrt
  vars_files:
    - group_vars/global_vars.yaml
    - host_vars/banana_pi_r3.yaml
  roles:
    - host-setup

- name: Setup DHCP
  hosts: openwrt
  vars_files:
    - group_vars/global_vars.yaml
    - host_vars/banana_pi_r3.yaml
  roles:
    - dhcp

- name: Disable IPv6
  hosts: openwrt
  vars_files:
    - group_vars/global_vars.yaml
    - host_vars/banana_pi_r3.yaml
  roles:
    - role: disable-ipv6
      when: disable_ipv6 | bool
  tags:
    - ipv6

- name: Check for NVMe and mount it
  hosts: openwrt
  vars_files:
    - host_vars/banana_pi_r3.yaml
  roles:
    - nvme
  tags:
    - nvme

- name: Install Luci with NGinx and SSL
  hosts: openwrt
  vars_files:
    - host_vars/banana_pi_r3.yaml
  roles:
    - additional-packages

- name: Copy and register our own Certificate Authority
  hosts: openwrt
  vars_files:
    - group_vars/global_vars.yaml
    - host_vars/banana_pi_r3.yaml
  roles:
    - certificates

- name: Configure PowerDNS and its recursor
  hosts: openwrt
  gather_facts: true
  vars_files:
    - host_vars/banana_pi_r3.yaml
    - group_vars/global_vars.yaml
  roles:
    - pdns
  tags:
    - pdns

- name: Configure vsftpd
  hosts: openwrt
  gather_facts: true
  vars_files:
    - host_vars/banana_pi_r3.yaml
    - group_vars/global_vars.yaml
  roles:
    - role: vsftpd
      when: vsftpd_install | bool
  tags:
    - vsftpd
