---
- name: Bootstrap python on Banana PI/OpenWRT
  hosts: openwrt
  gather_facts: false
  become: false
  vars_files:
    - host_vars/banana_pi_r3.yaml
  roles:
    - role: 'johanneskastl.bootstrap_python_on_OpenWRT'

- name: Setup the host
  hosts: openwrt
  vars_files:
    - group_vars/global_vars.yaml
    - host_vars/banana_pi_r3.yaml
  roles:
    - bpi-r3-host-setup

- name: Installing mandatory packages, block devices and filesystem manipulation
  hosts: openwrt
  vars_files:
    - host_vars/banana_pi_r3.yaml
  roles:
    - bpi-r3-filesystem-packages

- name: Checking for NVMe and mounting it
  hosts: openwrt
  vars_files:
    - host_vars/banana_pi_r3.yaml
  roles:
    - bpi-r3-mount-nvme

- name: Disabling IPv6
  hosts: openwrt
  vars_files:
    - group_vars/global_vars.yaml
  roles:
    - role: bpi-r3-disable-ipv6
      when: disable_ipv6 == "true"

- name: Installing NGinx with SSL, Luci with NGinx, PowerDNS and other packages
  hosts: openwrt
  vars_files:
    - host_vars/banana_pi_r3.yaml
  roles:
    - bpi-r3-additional-packages

- name: Copying and registering our own Certificate Authority
  hosts: openwrt
  vars_files:
    - group_vars/global_vars.yaml
    - host_vars/banana_pi_r3.yaml
  roles:
    - bpi-r3-certs

- name: Generating LAN IP from default_CIDR and bpi_ip
  hosts: openwrt
  vars_files:
    - host_vars/banana_pi_r3.yaml
    - group_vars/global_vars.yaml
  tasks:
    - name: Extracting network component from default_CIDR
      ansible.builtin.shell: |
        set -o pipefail
        echo "{{ default_CIDR }}" |  awk 'BEGIN { FS = "." } ; {print $1"."$2"."$3}'
      register: network_component
      changed_when: network_component.rc != 0
    - name: Registering LAN ip address as bpi_lan_ip fact
      ansible.builtin.set_fact:
        bpi_lan_ip: "{{ network_component.stdout }}.{{ bpi_ip }}"
        bpi_network: "{{ network_component.stdout }}"
        cacheable: true

- name: Configuring PowerDNS and its recursor
  hosts: openwrt
  gather_facts: true
  vars_files:
    - host_vars/banana_pi_r3.yaml
    - group_vars/global_vars.yaml
  roles:
    - pdns-config
    - pdns-recursor-config
    - pdns-zones-add-records
  tags:
    - pdns

- name: Configuring vsftpd
  hosts: openwrt
  gather_facts: true
  vars_files:
    - host_vars/banana_pi_r3.yaml
    - group_vars/global_vars.yaml
  roles:
    - role: vsftpd-config
      when: vsftpd_install == "true"
