- name: Generating webserver-address from default_CIDR and bpi_ip
  ansible.builtin.shell: |
    set -o pipefail
    echo "{{ default_CIDR }}" |  awk 'BEGIN { FS = "." } ; {print $1"."$2"."$3"}'
  register: echo_content
  changed_when: echo_content.rc != 0

- name: Registering pdns_webserver_address as fact
  ansible.builtin.set_fact:
    pdns_webserver_address: "{{ echo_content.stdout }}.{{ bpi_ip }}"
    cacheable: true

- name: Removing old /etc/powerdns/pdns.conf file
  ansible.builtin.file:
    path: /etc/powerdns/pdns.conf
    state: absent

- name: Copying pdns.conf from template /etc/powerdns/pdns.conf-dist
  ansible.builtin.copy:
    src: /etc/powerdns/pdns.conf-dist
    dest: /etc/powerdns/pdns.conf
    owner: root
    group: root
    mode: '0644'

- name: Configuring SQLite as backend
  ansible.builtin.replace:
    path: /etc/powerdns/pdns.conf
    regexp: '^# launch=.*'
    replace: 'launch=gsqlite3'

- name: Configuring PowerDNS
  ansible.builtin.shell: |
    set -o pipefail
    #    sed 's/# launch=/launch=gsqlite3/' /etc/powerdns/pdns.conf-dist > /etc/powerdns/pdns.conf
    sed -i '/launch=gsqlite3/a gsqlite3-database={{ pdns_db_path }}/pdns.sqlite3' /etc/powerdns/pdns.conf
    sed -i 's/# api=no/api=yes/' /etc/powerdns/pdns.conf
    API_KEY=`grep -ao '[A-Za-z0-9]' < /dev/urandom | head -64 | tr -d '\n' ; echo ""`
    sed -i "s/# api-key=/api-key=$API_KEY/" /etc/powerdns/pdns.conf
    sed -i "s/# webserver=.*/webserver=yes/" /etc/powerdns/pdns.conf
    sed -i "s/# webserver-address=.*/webserver-address={{ pdns_webserver_address }}/" /etc/powerdns/pdns.conf
    sed -i "s/# webserver-allow-from=.*/webserver-allow-from={{ pdns_allow_from }}/" /etc/powerdns/pdns.conf
    sed -i 's/^.* loglevel=.*/loglevel=8/' /etc/powerdns/pdns.conf
    sed -i 's/# logging-facility=.*/logging-facility=4/' /etc/powerdns/pdns.conf
    #   sed -i 's/^.* webserver-loglevel=.*/webserver-loglevel=detailed/' /etc/powerdns/pdns.conf
    #   /etc/init.d/pdns restart
    exit 0
  register: my_output
  changed_when: my_output.rc != 0

- name: Reload PowerDNS service
  community.general.openwrt_init:
    name: pdns
    state: reloaded
