---
- name: Removing old /etc/powerdns/recursor.conf file
  ansible.builtin.file:
    path: /etc/powerdns/recursor.conf
    state: absent

- name: Copying pdns.conf from template /etc/powerdns/recursor.conf-dist
  ansible.builtin.copy:
    src: /etc/powerdns/recursor.conf-dist
    dest: /etc/powerdns/recursor.conf
    owner: root
    group: root
    mode: '0644'
    remote_src: true

- name: Configuring allow-from localhost and default_CIDR
  ansible.builtin.replace:
    path: /etc/powerdns/recursor.conf
    regexp: '^# allow-from=.*'
    replace: "allow-from=127.0.0.0/8, {{ default_CIDR }}"

- name: Configuring socket-dir to /var/run/pdns
  ansible.builtin.replace:
    path: /etc/powerdns/recursor.conf
    regexp: '^# socket-dir=.*'
    replace: "socket-dir=/var/run/pdns"

- name: Setting config-dir
  ansible.builtin.replace:
    path: /etc/powerdns/recursor.conf
    regexp: '^# config-dir=.*'
    replace: 'config-dir=/etc/powerdns/'

- name: Setting dont-query for localhost
  ansible.builtin.replace:
    path: /etc/powerdns/recursor.conf
    regexp: '^# dont-query=.*'
    replace: 'dont-query=127.0.0.0/8'

- name: Setting forward zones for {{ default_domain }}
  ansible.builtin.replace:
    path: /etc/powerdns/recursor.conf
    regexp: '^# forward-zones=.*'
    replace: "forward-zones={{ default_domain }}=127.0.0.1:5300"

- name: Setting forward zones for {{ default_domain }}
  ansible.builtin.lineinfile:
    path: /etc/powerdns/recursor.conf
    search_string: '^$'
    insertafter: "forward-zones={{ default_domain }}=127.0.0.1:5300"
    line: "forward-zones+={{ in_addr_arpa }}=127.0.0.1:5300"

- name: Listerning only to local IP
  ansible.builtin.replace:
    path: /etc/powerdns/recursor.conf
    regexp: '^# local-address=.*'
    replace: "local-address=127.0.0.1,{{ ansible_facts['bpi_network'] }}.{{ ns1 }}"

- name: Port to listen on
  ansible.builtin.replace:
    path: /etc/powerdns/recursor.conf
    regexp: '^# local-port=.*'
    replace: "local-port=53"

- name: Enabling PowerDNS recursor service
  community.general.openwrt_init:
    name: pdns-recursor
    enabled: true

- name: Reload PowerDNS recursor service
  community.general.openwrt_init:
    name: pdns-recursor
    state: restarted
