---
- name: Run opkg update
  ansible.builtin.command: opkg update
  ignore_errors: true
  register: opkg_update
  changed_when: opkg_update.rc == 0

- name: Install package openssh-sftp-server to remove warning
  community.general.opkg:
    name: openssh-sftp-server
    state: present
  when: sftp_install | bool

- name: Install package openssl-util required for generating hash
  community.general.opkg:
    name:
      - openssl-util
    state: present

- name: Upgrade packages
  ansible.builtin.shell: |
    set -o pipefail
    opkg list-upgradable | cut -f 1 -d ' ' | xargs -r opkg upgrade
  register: upgrade_packages
  changed_when: upgrade_packages.rc == 0

- name: Add EDITOR=vi in /etc/profile
  ansible.builtin.blockinfile:
    path: /etc/profile
    insertafter: "EOF"
    block: |
      export EDITOR="vi"
    marker: "# {mark} editor ANSIBLE MANAGED BLOCK"

- name: Copy authorized_keys to /etc/dropbear
  ansible.builtin.copy:
    src: "{{ authorized_keys_path }}"
    dest: /etc/dropbear
    owner: root
    group: root
    mode: "0644"

- name: Change root password
  ansible.builtin.user:
    name: root
    update_password: always
    password: "{{ bpi_password | password_hash('sha512') }}"

# - name: Add own records to /etc/hosts
#   ansible.builtin.blockinfile:
#     path: /etc/hosts
#     insertafter: "EOF"
#     block: |
#       192.168,uuuu
#     marker: "# {mark} editor ANSIBLE MANAGED BLOCK"
