---
- name: Removing odhcpd-ipv6only
  community.general.opkg:
    name:
      - odhcpd-ipv6only
    state: absent

- name: Retrieving the number of interfaces
  ansible.builtin.shell: |
    set -o pipefail
    uci show network | grep '@device' | cut -f1 -d']' | cut -f2 -d'[' | sort -ru | head -1
  register: if_count
  changed_when: if_count.rc != 0

- name: UCI -- set ipv6=0 for all interfaces
  ansible.builtin.command: "uci set network.@device[{{ item }}].ipv6='0'"
  with_sequence: start=0 end={{ if_count.stdout | int }} stride=1
  register: set_ipv6
  changed_when: set_ipv6.rc == 0

- name: UCI -- set network.loopback.ipv6=0
  ansible.builtin.command: uci -q set network.loopback.ipv6='0'
  register: uci_set_network
  changed_when: uci_set_network.rc == 0

- name: UCI -- delete network.wan6
  ignore_errors: true
  ansible.builtin.command: uci -q delete network.wan6
  register: uci_del_network
  changed_when: uci_del_network.rc == 0

- name: UCI -- delete network.lan.ip6assign
  ignore_errors: true
  ansible.builtin.command: uci -q delete network.lan.ip6assign
  register: uci_del_network
  changed_when: uci_del_network.rc == 0

- name: UCI -- delete network.globals.ula_prefix
  ignore_errors: true
  ansible.builtin.command: uci -q delete network.globals.ula_prefix
  register: uci_del_network
  changed_when: uci_del_network.rc == 0

- name: UCI -- commit network
  ansible.builtin.command: uci commit network
  register: commit_network
  changed_when: commit_network.rc == 0

- name: Restarting network
  community.general.openwrt_init:
    name: network
    state: restarted

- name: UCI -- set 'dhcp.lan.dhcpv6=disabled'
  ansible.builtin.command: uci -q set dhcp.lan.dhcpv6=disabled
  register: set_dhcp
  changed_when: set_dhcp.rc == 0

- name: UCI -- delete dhcp.lan.dhcpv6
  ansible.builtin.command: uci -q delete dhcp.lan.dhcpv6
  register: delete_dhcp
  changed_when: delete_dhcp.rc == 0

- name: UCI -- delete dhcp.lan.ra
  ignore_errors: true
  ansible.builtin.command: uci -q delete dhcp.lan.ra
  register: delete_dhcp
  changed_when: delete_dhcp.rc == 0

- name: UCI -- commit dhcp
  ansible.builtin.command: uci commit dhcp
  register: commit_dhcp
  changed_when: commit_dhcp.rc == 0

- name: Restarting odhcpd
  community.general.openwrt_init:
    name: odhcpd
    state: restarted
  when: replace_dnsmasq_with_odhcpd == "true"

- name: Restarting dnsmasq
  community.general.openwrt_init:
    name: dnsmasq
    state: restarted
  when: replace_dnsmasq_with_odhcpd == "false"
