---
network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: no
      addresses:
        - 192.168.72.190/24
      gateway4: 192.168.72.1
      nameservers:
        addresses: [192.168.72.1]
