---
- name: Bootstrap python on Banana PI/OpenWRT
  hosts: openwrt
  gather_facts: false
  become: false
  vars_files:
    - vars/banana_pi_r3.yaml
  roles:
    - role: 'johanneskastl.bootstrap_python_on_OpenWRT'

- name: Host setup
  hosts: openwrt
  vars_files:
    - vars/global_vars.yaml
    - vars/banana_pi_r3.yaml
  roles:
    - host_setup
  tags:
    - host-setup

- name: Setup DHCP
  hosts: openwrt
  vars_files:
    - vars/global_vars.yaml
    - vars/banana_pi_r3.yaml
  roles:
    - dhcp_config

- name: Disable IPv6
  hosts: openwrt
  vars_files:
    - vars/global_vars.yaml
    - vars/banana_pi_r3.yaml
  roles:
    - role: disable_ipv6
      when: disable_ipv6 | bool
  tags:
    - ipv6

- name: Check for NVMe and mount it
  hosts: openwrt
  vars_files:
    - vars/banana_pi_r3.yaml
  roles:
    - OpenWRT_nvme
  tags:
    - nvme

- name: Install Prometheus Node Exporter
  hosts: openwrt
  vars_files:
    - vars/banana_pi_r3.yaml
  roles:
    - role: OpenWRT_prometheus_exporter
      when: prometheus_exporter_install | bool


- name: Install Luci with NGinx and SSL
  hosts: openwrt
  vars_files:
    - vars/banana_pi_r3.yaml
  roles:
    - OpenWRT_luci_nginx_ssl

- name: Copy and register already created own Certificate Authority
  hosts: openwrt
  vars_files:
    - vars/global_vars.yaml
    - vars/banana_pi_r3.yaml
  roles:
    - certificates

- name: Configure PowerDNS and its recursor
  hosts: openwrt
  gather_facts: true
  vars_files:
    - vars/banana_pi_r3.yaml
    - vars/global_vars.yaml
  roles:
    - OpenWRT_PowerDNS
  tags:
    - pdns

- name: Configure vsftpd
  hosts: openwrt
  gather_facts: true
  vars_files:
    - vars/banana_pi_r3.yaml
    - vars/global_vars.yaml
  roles:
    - role: OpenWRT_vsftpd
      when: vsftpd_install | bool
  tags:
    - vsftpd

- name: Create Docker Registry
  hosts: openwrt
  gather_facts: true
  vars_files:
    - vars/banana_pi_r3.yaml
    - vars/global_vars.yaml
  roles:
    - role: OpenWRT_docker
      when: docker_registry_install | bool
  tags:
    - docker_registry


- name: Configure openVPN
  hosts: openwrt
  gather_facts: true
  vars_files:
    - vars/banana_pi_r3.yaml
    - vars/global_vars.yaml
  roles:
    - role: OpenWRT_OpenVPN
      when: openvpn_install | bool
  tags:
    - openvpn
