---
- name: Installing openssh-sftp-server
  community.general.opkg:
    name: openssh-sftp-server
    state: present
  when: install_sftp == "true"

- name: Install openssl-util
  community.general.opkg:
    name:
      - openssl-util
    state: present

- name: Upgrading packages
  ansible.builtin.shell: |
    set -o pipefail
    opkg list-upgradable | cut -f 1 -d ' ' | xargs -r opkg upgrade
  register: upgrade_packages
  changed_when: upgrade_packages.rc == 0

- name: Adding EDITOR=vi in /etc/profile
  ansible.builtin.blockinfile:
    path: /etc/profile
    insertafter: "EOF"
    block: |
      export EDITOR="vi"
    marker: "# {mark} editor ANSIBLE MANAGED BLOCK"

- name: Copying authorized_keys to /etc/dropbear
  ansible.builtin.copy:
    src: "{{ authorized_keys_path }}"
    dest: /etc/dropbear
    owner: root
    group: root
    mode: "0644"

- name: Changing root password
  ansible.builtin.user:
    name: root
    update_password: always
    password: "{{ bpi_password | password_hash('sha512') }}"
