---
- name: Install filesystem manipulation packages
  community.general.opkg:
    name:
      - kmod-nvme
      - mmc-utils
      - kmod-mtd-rw
      - lsblk
      - parted
      - uvol
      - autopart
    state: present
