---
- name: Run opkg update
  ansible.builtin.command: opkg update
  ignore_errors: true
  register: opkg_update
  changed_when: opkg_update.rc == 0

- name: Install Prometheus exporter
  community.general.opkg:
    name:
      - prometheus-node-exporter-lua
      - prometheus-node-exporter-lua-nat_traffic
      - prometheus-node-exporter-lua-netstat
      - prometheus-node-exporter-lua-openwrt
      - libiwinfo-lua
      - prometheus-node-exporter-lua-wifi
      - prometheus-node-exporter-lua-wifi_stations
    state: present
  when: install_prometheus_exporter | bool

- name: Remove luci and dependencies
  community.general.opkg:
    name:
      - luci
      - luci-ssl
      - luci-light
    state: absent

- name: Install NGinx with SSL and luci-ssl-nginx
  community.general.opkg:
    name:
      - nginx-ssl
      - luci-ssl-nginx
      - luci-app-statistics
      - luci-app-upnp
      - luci-lib-nixio
      - luci-lib-ip
      - luci-lib-jsonc
      - liblucihttp-lua
      - luci-lib-base
      - ucode-mod-lua
      - luci-lua-runtime
      - luci-compat
    state: present

- name: Install OpenVPN packages
  community.general.opkg:
    name:
      - openvpn-openssl
      - openvpn-easy-rsa
      - luci-app-openvpn
    state: present
  when: install_openvpn | bool

- name: Install PowerDNS packages
  community.general.opkg:
    name:
      - pdns
      - pdns-recursor
      - pdns-backend-sqlite3
      - libedit
      - sqlite3-cli
    state: present
