---
- name: Create key, Certificate Authority, certificates and keys
  hosts: all
  connection: local
  gather_facts: false

  tasks:
    - name: Check if private key for CA exists.
      ansible.builtin.stat:
        path: ../files/cert/CA.key
      register: ca_key

    - name: Generate CA key.
      community.crypto.openssl_privatekey:
        path: ../files/certs/CA.key
      when: ca_key.stat.exists is false

    - name: Check if the self-signed certificate exists
      ansible.builtin.stat:
        path: ../files/certs/CA.pem
      register: ca_pem

    - name: Create certificate signing request (CSR) for self-signed certificate
      community.crypto.openssl_csr_pipe:
        privatekey_path: ../files/certs/CA.key
        common_name: lan
        organization_name: Home of the S.
      register: csr
      when: ca_pem.stat.exists is false

    - name: Create self-signed certificate from CSR
      community.crypto.x509_certificate:
        path: ../files/certs/CA.pem
        csr_content: "{{ csr.csr }}"
        privatekey_path: ../files/certs/CA.key
        provider: selfsigned
      when: ca_pem.stat.exists is false

    - name: Check if private key for bpi.home exists.
      ansible.builtin.stat:
        path: ../files/cert/bpi_home.key
      register: bpi_home_key

    - name: Generate bpi.home key.
      community.crypto.openssl_privatekey:
        path: ../files/certs/bpi_home.key
      when: bpi_home_key.stat.exists is false

    - name: Check if the self-signed certificate  for bpi.home exists
      ansible.builtin.stat:
        path: ../files/certs/bpi_home.pem
      register: bpi_home_pem

    - name: Create certificate signing request (CSR) for bpi.home certificate
      community.crypto.openssl_csr_pipe:
        privatekey_path: ../files/certs/bpi_home.key
        common_name: bpi.home
      register: csr_bpi_home
      when: bpi_home_pem.stat.exists is false

    - name: Create self-signed certificate from CSR
      community.crypto.x509_certificate:
        path: ../files/certs/bpi_home.pem
        csr_content: "{{ csr_bpi_home.csr }}"
        privatekey_path: ../files/certs/bpi_home.key
        provider: ownca
        ownca_path: ../files/certs/CA.pem
        ownca_privatekey_path: ../files/certs/CA.key
      when: bpi_home_pem.stat.exists is false

