---
- name: Create key and Certificate Authority.
  hosts: all
  connection: local
  gather_facts: false

  tasks:
    - name: Check if key exists.
      ansible.builtin.stat:
        path: ../files/cert/CA.key
      register: ca_key

    - name: Generate CA key.
      community.crypto.openssl_privatekey:
        path: ../files/certs/CA.key
      when: ca_key.stat.exists is false

    - name: Check if the self-signed certificate exists
      ansible.builtin.stat:
        path: ../files/certs/CA.pem
      register: ca_pem

    - name: Create certificate signing request (CSR) for self-signed certificate
      community.crypto.openssl_csr_pipe:
        privatekey_path: ../files/certs/CA.key
        common_name: lan
        organization_name: Home of the S.
      register: csr
      when: ca_pem.stat.exists is false

    - name: Create self-signed certificate from CSR
      community.crypto.x509_certificate:
        path: ../files/certs/CA.pem
        csr_content: "{{ csr.csr }}"
        privatekey_path: ../files/certs/CA.key
        provider: selfsigned
      when: ca_pem.stat.exists is false
