---
- name: Creating in-addr.arpa zone name
  ansible.builtin.shell: |
    set -o pipefail
    echo "{{ default_CIDR }}" |  awk 'BEGIN { FS = "." } ; {print $3"."$2"."$1".in-addr.arpa"}'
  register: in_addr
  changed_when: in_addr.rc == 0

- name: Registering in-addr.arpa as fact
  ansible.builtin.set_fact:
    in_addr_arpa: "{{ in_addr.stdout }}"
    cacheable: true

- name: Removing old /etc/powerdns/recursor.conf file if it exists
  ansible.builtin.file:
    path: /etc/powerdns/recursor.conf
    state: absent

- name: Copying /etc/powerdns/recursor.conf from template /etc/powerdns/recursor.conf-dist
  ansible.builtin.copy:
    src: /etc/powerdns/recursor.conf-dist
    dest: /etc/powerdns/recursor.conf
    owner: root
    group: root
    mode: '0644'
    remote_src: true

- name: Configuring allow-from localhost and default_CIDR
  ansible.builtin.replace:
    path: /etc/powerdns/recursor.conf
    regexp: '^# allow-from=.*'
    replace: "allow-from=127.0.0.0/8, {{ default_CIDR }}"

- name: Configuring socket-dir to /var/run/pdns
  ansible.builtin.replace:
    path: /etc/powerdns/recursor.conf
    regexp: '^# socket-dir=.*'
    replace: "socket-dir=/var/run/pdns"

- name: Setting config-dir
  ansible.builtin.replace:
    path: /etc/powerdns/recursor.conf
    regexp: '^# config-dir=.*'
    replace: 'config-dir=/etc/powerdns/'

- name: Setting forward zones
  ansible.builtin.replace:
    path: /etc/powerdns/recursor.conf
    regexp: '^# forward-zones=.*'
    replace: "forward-zones={{ default_domain }}=127.0.0.1:5300, {{ in_addr_arpa }}=127.0.0.1:5300"

- name: Listerning only to local IP
  ansible.builtin.replace:
    path: /etc/powerdns/recursor.conf
    regexp: '^# local-address=.*'
    replace: "local-address=127.0.0.1,{{ ansible_facts['bpi_network'] }}.{{ ns1 }}"

- name: Port to listen on
  ansible.builtin.replace:
    path: /etc/powerdns/recursor.conf
    regexp: '^# local-port=.*'
    replace: "local-port=53"

- name: Enabling serve-rfc1918
  ansible.builtin.replace:
    path: /etc/powerdns/recursor.conf
    regexp: '^# serve-rfc1918=.*'
    replace: "serve-rfc1918=yes"

- name: Setting search suffix to {{ default_domain }}
  ansible.builtin.replace:
    path: /etc/powerdns/recursor.conf
    regexp: '^# export-etc-hosts-search-suffix=.*'
    replace: "export-etc-hosts-search-suffix={{ default_domain }}"

- name: Enabling PowerDNS recursor service
  community.general.openwrt_init:
    name: pdns-recursor
    enabled: true

- name: Restarting PowerDNS recursor service
  community.general.openwrt_init:
    name: pdns-recursor
    state: restarted
