---
- name: Updating OS on the Banana Pi R3
  ansible.builtin.shell: |
    wget {{ bpi_image_url }} -O /tmp/sysupgrade.itb
    sysupgrade -v /tmp/sysupgrade.itb
  when: bpi_os_upgrade == "true"
  register: my_output
  changed_when: my_output.rc != 0

- name: Wait for the reboot to complete
  ansible.builtin.wait_for_connection:
    connect_timeout: 10
    sleep: 5
    delay: 5
    timeout: 300
  when: bpi_os_upgrade is true
